version: '3'

services:
  web:
    build:
      context: dockerfiles
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:80

  app:
    build:
      context: dockerfiles
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - 9000
    environment:
      DB_HOST: dbpq
      DB_PORT: 5432

  dbpq:
    image: postgres:10.5
    restart: always
    volumes:
    - ./dockerfiles/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: homestead
      POSTGRES_DB: homestead
    expose:
    - 5432

  adminer:
    image: adminer
    restart: always
    ports:
    - 8002:8080

volumes:
  db: